apiVersion: apps/v1
kind: Deployment

# 기본 설정
metadata:
  name: pinhouse-be

# 스펙
spec:
  # Replica 개수
  replicas: 0

  # 라벨
  template:
    metadata:
      labels:
        environment: prod

    # 컨테이너 스펙
    spec:
      containers:
        - name: pinhouse-be

          # 자원 제한은 미정
