apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 네임 스페이스
namespace: app

resources:
  - ../../../base/backend
  - httproute.yaml

nameSuffix: -prod

# 이미지 수정
# ArgoCD Image Updater가 자동으로 newTag를 업데이트
images:
  - name: REPLACE_ME
    newName: asia-northeast3-docker.pkg.dev/prod-pinhouse/pinhouse-prod-be
    newTag: latest

# overlays 수정내용 반영
patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pinhouse-be
