apiVersion: apps/v1
kind: Deployment

# 기본 정보
metadata:
  name: pinhouse-fe

# 스펙
spec:
  replicas: 2
  # RS 최근 3개 버전만 보관
  revisionHistoryLimit: 3

  # 배포 전략: Zero-downtime Rolling Update
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # 삭제 되는 Pod 수
      maxSurge: 1        # 업데이트를 위해서 1개의 Pod 추가

  # 셀렉터
  selector:
    matchLabels:
      app: frontend

  # 라벨
  template:
    metadata:
      labels:
        app: frontend

    # 컨테이너 스펙
    spec:
      containers:
        - name: pinhouse-fe

          # 수정될 이미지
          image: REPLACE_ME
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
