# ===================================
# Image Updator
# ===================================

apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater

# 기본 정보
metadata:
  name: prod-applications
  namespace: argocd

spec:
  # 라벨 기반 어플리케이션 적용
  applicationRefs:
    - namePattern: "*"

      # 라벨 추가
      labelSelectors:
        matchLabels:
          pinhouse.co.kr/image-updater: enabled
          pinhouse.co.kr/environment: prod
      useAnnotations: true
