# ===================================
# Dev Platform cert-manager
# ===================================

apiVersion: argoproj.io/v1alpha1
kind: Application

# 기본 정보
metadata:
  name: platform-cert-manager-dev
  namespace: argocd
  labels:
    pinhouse.co.kr/environment: dev
    pinhouse.co.kr/component: platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

# 스펙
spec:
  project: default

  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.16.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/k8s-helm/releases/cert-manager/values-nonprod.yaml
    - repoURL: https://github.com/PinHouse/PinHouse_CLOUD
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
