# ===================================
# Dev Platform GCE PD CSI Driver
# ===================================

apiVersion: argoproj.io/v1alpha1
kind: Application

# 기본 정보
metadata:
  name: platform-gce-pd-csi-driver-dev
  namespace: argocd
  labels:
    pinhouse.co.kr/environment: dev
    pinhouse.co.kr/component: platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

# 스펙
spec:
  project: default

  source:
    repoURL: https://github.com/PinHouse/PinHouse_CLOUD
    targetRevision: main
    path: k8s-kustomize/platform/gce-pd-csi-driver

  destination:
    server: https://kubernetes.default.svc
    namespace: gce-pd-csi-driver

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
