# 게이트웨이 설정
{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:

    # HTTP 포트 (80) - HTTPS 리다이렉트 또는 일반 HTTP 트래픽용
    {{- if or .Values.gateway.http.enabled .Values.gateway.http_redirect.enabled }}
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}

    # 환경 체크
    {{- range $env := .Values.gateway.environments }}

    # true인 환경
    {{- if $env.enabled }}

    # 반복문 진행
    {{- range $service := $env.services }}

    # 443 포트 적용
    - name: {{ $env.name }}-{{ $service.name }}-https
      port: 443
      protocol: HTTPS
      hostname: {{ $service.hostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ $env.tlsSecretName }}
            namespace: {{ $.Values.gateway.namespace }}
      allowedRoutes:
        namespaces:
          from: All
    # 반복문 종료
    {{- end }}

    # true 환경
    {{- end }}

    # 환경 체크
    {{- end }}

    {{- if .Values.gateway.listeners.argo.enabled }}
    # Argo CD
    - name: argo-https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.gateway.listeners.argo.domain }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.listeners.argo.tlsSecretName }}
            namespace: {{ .Values.gateway.namespace }}
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}

    {{- if .Values.gateway.listeners.grafana.enabled }}
    # Grafana 모니터링
    - name: grafana-https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.gateway.listeners.grafana.domain }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.listeners.grafana.tlsSecretName }}
            namespace: {{ .Values.gateway.namespace }}
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}

{{- end }}
