# ===================================
# Prod Platform Argo CD Config
# ===================================

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform-argocd-config-prod
  namespace: argocd
  labels:
    pinhouse.co.kr/environment: prod
    pinhouse.co.kr/component: platform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/PinHouse/PinHouse_CLOUD
    targetRevision: main
    path: k8s-kustomize/platform/argocd/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
