# ExternalSecret 리소스 구현
{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secrets }}

  # 반복문 전체
{{- range $secret := .Values.externalSecrets.secrets }}
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret

# 기본 정보
metadata:
  name: {{ required "🚨 에러: Secret의 name 값이 빠졌습니다!" $secret.name }}

  # 네임 스페이스
  namespace: {{ required "🚨 에러: Secret의 namespace 값이 빠졌습니다!" $secret.namespace }}

  #라벨
  {{- with $secret.labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}

  # 어노테이션
  {{- with $secret.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}

# 스펙
spec:{{ toYaml (required "🚨 에러: Secret의 spec 값이 빠졌습니다!" $secret.spec) | nindent 2 }}

# 반복문 전체
{{- end }}

# ESO 설정 종료
{{- end }}
