# ESO 설정 구현

{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStores }}

# 반복문 시작
{{- range $store := .Values.externalSecrets.secretStores }}
---

# ClusterSecretStore
apiVersion: external-secrets.io/v1
kind: {{ default "ClusterSecretStore" $store.kind }}

# 기본 정보
metadata:
  name: {{ required "🚨 에러: Secret의 name 값이 빠졌습니다!" $store.name }}

  {{- if and (eq (default "ClusterSecretStore" $store.kind) "SecretStore") $store.namespace }}
  namespace: {{ $store.namespace }}
  {{- end }}

  # 라벨
  {{- with $store.labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}

  # 어노테이션
  {{- with $store.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}

# 스펙 정리
spec:{{ toYaml (required "🚨 에러: Secret의 spec 값이 빠졌습니다!" $store.spec) | nindent 2 }}

# 반복문 종료
{{- end }}

# ESO 종료
{{- end }}
